src/main/java/org/imixs/application/ui/StatsController.java
/*******************************************************************************
 *  Imixs Workflow Technology
 *  Copyright (C) 2003, 2008 Imixs Software Solutions GmbH,  
 *  http://www.imixs.com
 *  
 *  This program is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU General Public License 
 *  as published by the Free Software Foundation; either version 2 
 *  of the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 *  General Public License for more details.
 *  
 *  You can receive a copy of the GNU General Public
 *  License at http://www.gnu.org/licenses/gpl.html
 *  
 *  Contributors:  
 *  	Imixs Software Solutions GmbH - initial API and implementation
 *  	Ralph Soika
 *  
 *******************************************************************************/
package org.imixs.application.ui;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ConversationScoped;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.inject.Named;

import org.imixs.workflow.engine.DocumentService;
import org.imixs.workflow.engine.ModelService;
import org.imixs.workflow.engine.index.Category;
import org.imixs.workflow.engine.index.SearchService;
import org.imixs.workflow.exceptions.AccessDeniedException;
import org.imixs.workflow.exceptions.ModelException;
import org.imixs.workflow.exceptions.QueryException;
import org.imixs.workflow.faces.data.WorkflowEvent;

/**
 * The StatsController collects statistics data for 
 * the active process instances.
 * 
 * @see workitem_chronicle.xhtml
 * @author rsoika,gheinle
 */
@Named
@ConversationScoped
public class StatsController implements Serializable {

	int eventCount=0;
	
	private static final long serialVersionUID = 1L;
	
	@Inject
	protected DocumentService documentService;
	
	@Inject
	protected ModelService modelService;
	
	@Inject
	protected SearchService searchService; 
	
	private static Logger logger = Logger.getLogger(StatsController.class.getName());

	
	
	@PostConstruct
	public void init() {
		
		try {
			eventCount=documentService.count("type:workitem");
		} catch (QueryException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	
	/**
     * WorkflowEvent listener to update the current FormDefinition.
     * 
     * @param workflowEvent
     * @throws AccessDeniedException
     * @throws ModelException
     */
    public void onWorkflowEvent(@Observes WorkflowEvent workflowEvent) {
        if (workflowEvent == null)
            return;


        int eventType = workflowEvent.getEventType();
        if (WorkflowEvent.WORKITEM_CHANGED == eventType || WorkflowEvent.WORKITEM_CREATED == eventType
                || WorkflowEvent.WORKITEM_AFTER_PROCESS == eventType) {
            //reset 
            init();
        }

    }


	public int getEventCount() {
		return eventCount;
	}


	public void setEventCount(int eventCount) {
		this.eventCount = eventCount;
	}

	public int getModelCount() {
		return modelService.getVersions().size();
	}
	
	
	public String getStats() {
		
		String result="status: ";
		List<Category> categories = searchService.getTaxonomy("device","$workflowstatus");
		
		for (Category category: categories) {
			result=result+category.getName() + " = " + category.getCount()  + "\n";
			Map<String, Integer> labels = category.getLabels();
			for (Map.Entry<String, Integer> entry : labels.entrySet()) {
			    result=result+"       "+ entry.getKey()+ " = " + entry.getValue()  + "\n";
			}
		}
		
		return result;
	}
	
	public Map<String, Integer> getLabels(String name) {
		List<Category> categories = searchService.getTaxonomy(name);
		
		if (categories!=null && categories.size()>0) {
			return categories.get(0).getLabels();
		}
		
		return null;
		
		
	}
   
	
	
	   /**
     * 
     * <pre>
     *  {
            labels : [ 'Red', 'Blue', 'Yellow' ],
            datasets : [ {
                label : 'My First Dataset',
                data : [ 300, 50, 100 ],
                backgroundColor : [
                        'rgb(255, 99, 132)',
                        'rgb(54, 162, 235)',
                        'rgb(255, 205, 86)' ]
            } ]
        }
     * </pre>
     * 
     * @return
     */
    public String buildChartData(String group) {
    	
    	List<Category> categories = searchService.getTaxonomy(group);
		
		if (categories==null|| categories.size()==0) {
			return "";
		}
		
        Map<String, Integer> labels = categories.get(0).getLabels();
        // build a list of all lables....
        
        
        String result = "{";

        // Lables
        result = result + "labels : [ ";
        result = result + labels.keySet().stream().collect(Collectors.joining("','", "'", "'"));
        result = result + "],";

        // Datasets
        result = result + " datasets : [ { ";
        result = result + " label : '" + group + "', ";

        // build array of overall count
        List<String> statusCount = new ArrayList<String>();
        for (Map.Entry<String, Integer> entry : labels.entrySet()) {
        	statusCount.add(""+ entry.getValue() );
		}
        result = result + " data: [ " + statusCount.stream().collect(Collectors.joining(",")) + "],";

        // colors...
        result = result + " backgroundColor : [\n" + "                        'rgb(255, 99, 132)',\n"
                + "                        'rgb(54, 162, 235)',\n" + "                        'rgb(255, 205, 86)' ]";

        result = result + " } ] }";
        return result;
    }

}

src/main/webapp/layout/footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">

	<h:form>
		<ul>
			<li>Imixs IoT Monitor - (imixs-workflow v.#{message.application_workflow_build})</li>
		</ul>
	</h:form>
</ui:composition>

src/main/webapp/layout/head_container.xhtml
<f:subview xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">

	

<div class="container" style="width: 100%;">

			<div class="sub-container">

				<div class="sub-container-box">
					<h2>Welcome</h2>
					<!--  Singed in user -->
					<h:panelGroup rendered="#{loginController.authenticated}">
						<span class="typcn typcn-key"></span>
						<h:outputText value="Login: #{loginController.userPrincipal}" />
					</h:panelGroup>
					<br /> Last Login: 10.0.0.
				</div>
				<div class="sub-container-box" style="display: flex;">

					<div style="flex-grow: 1;">
						<h2>Models</h2>

						<h:outputLink value="/pages/admin/modellist.xhtml">
							<span class="typcn typcn-flow-merge"></span>
							<h:outputText value="All Models" />
						</h:outputLink>

					</div>

					<div style="flex-grow: 1; text-align: center;">
						<span style="font-size: 4em; font-weight: bold; line-height: 1em;">#{statsController.modelCount}</span>
					</div>



				</div>
				<div class="sub-container-box">
					<h2>User Management</h2>
					<h:outputLink value="/pages/admin/profilelist.xhtml">
						<span class="typcn typcn-user"></span>
						<h:outputText value="All Users" />
					</h:outputLink>
					<br />
					<h:outputLink value="/pages/admin/spaces.xhtml">
						<span class="typcn typcn-group"></span>
						<h:outputText value="All Groups" />
					</h:outputLink>
				</div>
			</div>
		</div>




</f:subview>

src/main/webapp/layout/header.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough">



	<div class="container title">
		<h:outputLink value="/pages/welcome.xhtml">
			<span class="typcn typcn-home"></span>
			<h:outputText value="Imixs IoT Monitor" />
		</h:outputLink>
	</div>


	<div class="container searchbox"> 
		<h:form
			onkeypress="if (event.keyCode == 13) { $('.header-search-button').click(); return false; }">

			<h:inputText style="width: 80%;" value="#{searchController.input}"
				a:placeholder="search..." />
			<h:commandLink actionListener="#{searchController.search()}"
				styleClass="header-search-button" action="/pages/search"
				title="#{global.search}">
				<span class="typcn typcn-zoom-outline"></span>
			</h:commandLink>
		</h:form>

	</div>
	
	
	<div class="container linkbox ">
		<div class="pull-right">

			<ul>
				<li><a href="https://www.imixs.org" target="_blank"><span
						class="typcn typcn-mortar-board"></span></a></li>

				<li><a href="https://github.com/imixs/imixs-iot-monitor"
					target="_blank"><span class="typcn typcn-social-github"></span></a></li>
			</ul>
		</div>
	</div>






</ui:composition>

src/main/webapp/layout/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta content="text/javascript" http-equiv="Content-Script-Type" />
	<meta content="text/css" http-equiv="Content-Style-Type" />
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
	<meta content="Imixs Workflow" name="keywords" />

	<title>#{message.application_title}</title>

	<i:imixsHeader disablecss="false"
		dateformat="#{message.datePatternShort}" disabletinymce="false"
		disablefileupload="false" />

	<!-- tinyMCE -->
	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/layout/js/tinymce/tinymce.min.js"></script>

	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/layout/js/imixs-core.js"></script>
	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/layout/js/imixs-xml.js"></script>
	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/layout/js/basic.js"></script>

	<!-- Load the marty component script -->
	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/marty/imixs-marty.js?build=#{app.application_build_timestamp}"></script>

	

	<!-- Fonts
	    ================================================== -->
	<link rel="stylesheet" type="text/css"
		href="#{facesContext.externalContext.requestContextPath}/layout/css/fonts/open_sans.css" />
	<link rel="stylesheet" type="text/css"
		href="#{facesContext.externalContext.requestContextPath}/layout/css/fonts/typicons.css" />

	<!-- layout -->
	<link
		href="#{facesContext.externalContext.requestContextPath}/layout/css/imixs-basic.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/layout/css/imixs-layout.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />

	<link
		href="#{facesContext.externalContext.requestContextPath}/marty/imixs-marty.css?build=#{app.application_build_timestamp}"
		charset="UTF-8" type="text/css" rel="stylesheet" />

	<link
		href="#{facesContext.externalContext.requestContextPath}/layout/css/basic.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/layout/css/chronicle.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />


	<!-- Charts  -->
	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/layout/js/chartjs/chart.min.js?build=#{app.application_build_timestamp}"></script>

	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/layout/js/imixs-charts.js?build=#{app.application_build_timestamp}"></script>


	
</h:head>
<h:body>



	<f:view>
		<f:loadBundle basename="bundle.message" var="message" />




		<!-- Page Content -->
		<div class="content">

			<div id="imixs-header">
				<ui:insert name="header">
					<ui:include src="header.xhtml" />
				</ui:insert>
			</div>


			<div id="imixs-content">
			
				<ui:include src="head_container.xhtml" />
			
				<ui:insert name="content">
					<h2>Default Content</h2>
				</ui:insert>
			</div>

			<div id="imixs-footer">
				<ui:insert name="footer">
					<ui:include src="footer.xhtml" />
				</ui:insert>
			</div>

		</div>
	</f:view>




	<script type="text/javascript">
		/*<![CDATA[*/

		$(document).ready(function() {
			layoutEditor();
		});

		/* laest sich im moment nicht auslagern (script_url!) see issue #87 */
		layoutEditor = function() {
			// Layout office default editor
			tinymce
					.init({
						selector : 'textarea.imixs-editor',
						height : 300,
						plugins : [
								'advlist autolink lists link image preview',
								'searchreplace code fullscreen',
								'contextmenu paste code' ],
						toolbar : 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
						content_css : "#{facesContext.externalContext.requestContextPath}/layout/css/tinymce.css"

					});

		};

		/*]]>*/
	</script>



</h:body>

</html>