src/main/java/org/imixs/application/model/ModelController.java
/*******************************************************************************
 *  Imixs Workflow 
 *  Copyright (C) 2001, 2011 Imixs Software Solutions GmbH,  
 *  http://www.imixs.com
 *  
 *  This program is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU General Public License 
 *  as published by the Free Software Foundation; either version 2 
 *  of the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 *  General Public License for more details.
 *  
 *  You can receive a copy of the GNU General Public
 *  License at http://www.gnu.org/licenses/gpl.html
 *  
 *  Project: 
 *  	http://www.imixs.org
 *  	http://java.net/projects/imixs-workflow
 *  
 *  Contributors:  
 *  	Imixs Software Solutions GmbH - initial API and implementation
 *  	Ralph Soika - Software Developer
 *******************************************************************************/

package org.imixs.application.model;

import java.io.IOException;
import java.io.Serializable;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.event.ActionEvent;
import javax.inject.Inject;
import javax.inject.Named;
import javax.xml.parsers.ParserConfigurationException;

import org.imixs.workflow.FileData;
import org.imixs.workflow.ItemCollection;
import org.imixs.workflow.Model;
import org.imixs.workflow.bpmn.BPMNModel;
import org.imixs.workflow.bpmn.BPMNParser;
import org.imixs.workflow.engine.ModelService;
import org.imixs.workflow.engine.SetupService;
import org.imixs.workflow.engine.WorkflowService;
import org.imixs.workflow.exceptions.AccessDeniedException;
import org.imixs.workflow.exceptions.ModelException;
import org.imixs.workflow.exceptions.PluginException;
import org.xml.sax.SAXException;

/**
 * The ModelController provides informations about workflow models.
 * 
 * A ModelVersion is always expected in the format
 * 
 * 'DOMAIN-LANGUAGE-VERSIONNUMBER'
 * 
 * e.g. office-de-0.1, support-en-2.0, system-de-0.0.1
 * 
 * 
 * @author rsoika
 * 
 */
@Named
@RequestScoped
public class ModelController implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	protected ModelUploadHandler modelUploadHandler;

	@EJB
	protected ModelService modelService;

	@EJB
	protected WorkflowService workflowService;

	@EJB
	protected SetupService setupService;

	private Map<String, ItemCollection> modelEntityCache = new HashMap<String, ItemCollection>();

	private static Logger logger = Logger.getLogger(ModelController.class.getName());


	/**
	 * returns all groups for a version
	 * 
	 * @param version
	 * @return
	 */
	public List<String> getGroups(String version) {
		try {
			return modelService.getModel(version).getGroups();
		} catch (ModelException e) {
			logger.warning("Unable to load groups:" + e.getMessage());
		}
		// return empty result
		return new ArrayList<String>();
	}

	/**
	 * Returns a String list of all WorkflowGroup names.
	 * 
	 * Workflow groups of the system model will be skipped.
	 * 
	 * A workflowGroup with a '~' in its name will be skipped. This indicates a
	 * child process.
	 * 
	 * The worflowGroup list is used to assign a workflow Group to a core process.
	 * 
	 * @return list of workflow groups
	 */
	public List<String> getWorkflowGroups() {

		Set<String> set = new HashSet<String>();
		List<String> versions = modelService.getVersions();
		for (String version : versions) {
			try {
				if (version.startsWith("system-"))
					continue;
				set.addAll(modelService.getModel(version).getGroups());
			} catch (ModelException e) {
				e.printStackTrace();
			}
		}
		List<String> result = new ArrayList<>();

		// add all groups without '~'
		for (String agroup : set) {
			if (result.contains(agroup))
				continue;
			if (agroup.contains("~"))
				continue;
			result.add(agroup);
		}

		Collections.sort(result);
		return result;

	}

	/**
	 * Returns a String list of all Sub-WorkflowGroup names for a specified
	 * WorkflowGroup.
	 * 
	 * 
	 * A SubWorkflowGroup contains a '~' in its name.
	 * 
	 * The SubWorflowGroup list is used to assign sub workflow Group to a workitem
	 * 
	 * @see getWorkflowGroups()
	 * 
	 * @param parentWorkflowGroup
	 *            - the parent workflow group name
	 * @return list of all sub workflow groups for the given parent group name
	 */
	public List<String> getSubWorkflowGroups(String parentWorkflowGroup) {

		Set<String> set = new HashSet<String>();
		List<String> versions = modelService.getVersions();
		for (String version : versions) {
			try {
				if (version.startsWith("system-"))
					continue;
				set.addAll(modelService.getModel(version).getGroups());
			} catch (ModelException e) {
				e.printStackTrace();
			}
		}
		List<String> result = new ArrayList<>();

		// add all groups starting with GROUP~
		for (String agroup : set) {
			if (result.contains(agroup))
				continue;
			if (!agroup.startsWith(parentWorkflowGroup + "~"))
				continue;
			result.add(agroup);
		}

		Collections.sort(result);
		return result;

	}

	public Model getModelByWorkitem(ItemCollection workitem) {
		try {
			return modelService.getModelByWorkitem(workitem);
		} catch (ModelException e) {
			return null;
		}
	}

	/**
	 * Returns a model object for corresponding workflow group.
	 * 
	 * @param group
	 * @return
	 */
	public Model getModelByGroup(String group) {
		List<String> versions = modelService.findVersionsByGroup(group);
		if (!versions.isEmpty()) {
			String version = versions.get(0);
			try {
				return modelService.getModel(version);
			} catch (ModelException e) {
				logger.warning(e.getMessage());
				return null;
			}
		}
		return null;
	}

	/**
	 * returns all model versions
	 * 
	 * @return
	 */
	public List<String> getVersions() {
		return modelService.getVersions();
	}

	public ItemCollection getModelEntity(String version) {

		ItemCollection result = modelEntityCache.get(version);
		if (result == null) {
			result = modelService.loadModelEntity(version);
			modelEntityCache.put(version, result);
		}

		return result;
	}

	/**
	 * This method adds all uploaded model files. The method tests the model type
	 * (.bmpm, .ixm). BPMN Model will be handled by the ImixsBPMNParser. A .ixm file
	 * will be imported using the default import mechanism.
	 * 
	 * @param event
	 * @throws IOException
	 * @throws SAXException
	 * @throws ParserConfigurationException
	 * @throws ParseException
	 * @throws ModelException
	 * 
	 */
	public void doUploadModel(ActionEvent event)
			throws ModelException, ParseException, ParserConfigurationException, SAXException, IOException {
		List<FileData> fileList = modelUploadHandler.getModelUploads().getFileData();

		if (fileList == null) {
			return;
		}
		for (FileData file : fileList) {
			logger.info("Import bpmn-model: " + file.getName());

			// test if bpmn model?
			if (file.getName().endsWith(".bpmn")) {
				BPMNModel model = BPMNParser.parseModel(file.getContent(), "UTF-8");
				modelService.saveModel(model);
				continue;
			}

			if (file.getName().endsWith(".ixm")) {
				setupService.importXmlEntityData(file.getContent());
				continue;
			}

			// model type not supported!
			logger.warning("Invalid Model Type. Model can't be imported!");

		}
		modelUploadHandler.reset();
	}

	/**
	 * This Method deletes the given model from the database and the internal model
	 * cache.
	 * 
	 * @throws AccessDeniedException
	 * @throws ModelException
	 */
	public void deleteModel(String modelversion) throws AccessDeniedException, ModelException {
		modelService.deleteModel(modelversion);
	}

	/**
	 * This method returns a process entity for a given ModelVersion or null if no
	 * entity exists.
	 * 
	 * 
	 * @param modelVersion
	 *            - version for the model to search the process entity
	 * @param processid
	 *            - id of the process entity
	 * @return an instance of the matching process entity
	 * @throws ModelException
	 */
	public ItemCollection getProcessEntity(int processid, String modelversion) {
		try {
			return modelService.getModel(modelversion).getTask(processid);
		} catch (ModelException e) {
			logger.warning("Unable to load task " + processid + " in model version '" + modelversion + "' - "
					+ e.getMessage());
		}
		return null;
	}

	/**
	 * This method return the 'rtfdescription' of a processentity and applies the
	 * dynamic Text replacement function from the jee plugin
	 * 
	 * @param processid
	 * @param modelversion
	 * @return
	 * @throws ModelException
	 */
	public String getProcessDescription(int processid, String modelversion, ItemCollection documentContext) {
		ItemCollection pe = null;
		try {
			pe = modelService.getModel(modelversion).getTask(processid);
		} catch (ModelException e1) {
			logger.warning("Unable to load task " + processid + " in model version '" + modelversion + "' - "
					+ e1.getMessage());

		}
		if (pe == null) {
			return "";
		}
		String desc = pe.getItemValueString("rtfdescription");

		try {
			desc = workflowService.adaptText(desc, documentContext);
		} catch (PluginException e) {
			logger.warning("Unable to update processDescription: " + e.getMessage());
		}

		return desc;

	}
}

src/main/webapp/pages/workflow/custom.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:marty="http://xmlns.jcp.org/jsf/composite/marty">


	<c:forEach items="#{customFormController.sections}" var="section">

		<c:if test="#{! empty section.label}">
			<h3>#{section.label}</h3>
		</c:if>
		<div
			class="imixs-form-section#{(empty section.columns)?'':'-'.concat(section.columns)}">



			<c:forEach items="#{section.items}" var="item">
				<dl>
					<dt>
						#{item.label}
						<c:if test="#{item.required}">
							<span class="imixs-required"> *</span>
						</c:if>
					</dt>
					<dd>
						<!-- text -->
						<c:if test="#{item.type eq 'text'}">
							<h:inputText value="#{workitem.item[item.name]}"
								pt:data-item="#{item.name}" required="#{item.required}"
								rendered="#{!item.readonly}" />
							<h:outputText value="#{workitem.item[item.name]}"
								rendered="#{item.readonly}" />
						</c:if>

						<!-- number -->
						<c:if test="#{item.type eq 'number'}">
							<h:inputText value="#{workitem.item[item.name]}"
								pt:data-item="#{item.name}" required="#{item.required}"
								rendered="#{!item.readonly}">
								<f:convertNumber />
							</h:inputText>
							<h:outputText value="#{workitem.item[item.name]}"
								rendered="#{item.readonly}">
								<f:convertNumber />
							</h:outputText>
						</c:if>

						<!-- currency -->
						<c:if test="#{item.type eq 'currency'}">
							<h:inputText value="#{workitem.item[item.name]}"
								pt:data-item="#{item.name}" required="#{item.required}"
								rendered="#{!item.readonly}">
								<f:convertNumber minFractionDigits="2" locale="de" />
							</h:inputText>
							<h:outputText value="#{workitem.item[item.name]}"
								rendered="#{item.readonly}">
								<f:convertNumber minFractionDigits="2" locale="de" />
							</h:outputText>
						</c:if>

						<!-- date -->
						<c:if test="#{item.type eq 'date'}">
							<h:inputText value="#{workitem.item[item.name]}"
								pt:data-item="#{item.name}" required="#{item.required}"
								styleClass="imixs-date" rendered="#{!item.readonly}">
								<f:convertDateTime pattern="#{message.datePatternShort}"
									timeZone="#{message.timeZone}" />
							</h:inputText>
							<h:outputText value="#{workitem.item[item.name]}" rendered="#{item.readonly}">
								<f:convertDateTime timeZone="#{message.timeZone}"
									pattern="#{message.datePatternShort}" />
							</h:outputText>
						</c:if>

						<!-- text area -->
						<c:if test="#{item.type eq 'textarea'}">
							<h:inputTextarea value="#{workitem.item[item.name]}"
								pt:data-item="#{item.name}" required="#{item.required}"
								rendered="#{!item.readonly}" />
							<h:outputText escape="true" value="#{workitem.item[item.name]}"
								rendered="#{item.readonly}" />
						</c:if>

						<!-- html -->
						<c:if test="#{item.type eq 'html'}">
							<h:inputTextarea required="#{item.required}"
								pt:data-item="#{item.name}" class="imixs-editor"
								value="#{workitem.item[item.name]}" rendered="#{!item.readonly}" />
							<h:outputText escape="false" value="#{workitem.item[item.name]}"
								rendered="#{item.readonly}" />
						</c:if>

						<!-- Options List -->
						<c:if
							test="#{item.type eq 'selectBooleanCheckbox' or item.type eq 'selectOneMenu' or item.type eq 'selectOneRadio' or item.type eq 'selectManyCheckbox'}">
							<c:choose>
								<!-- read only mode -->
								<c:when test="#{item.readonly}">
									<ui:repeat var="itemvalue"
										value="#{workitem.itemList[item.name]}">
										<h:outputText value="#{itemvalue}"></h:outputText>
										<br />
									</ui:repeat>
								</c:when>
								<!-- Edit mode -->
								<c:otherwise>
									<c:if test="#{item.type eq 'selectBooleanCheckbox'}">
										<h:selectBooleanCheckbox required="#{item.required}"
											pt:data-item="#{item.name}"
											value="#{workitem.item[item.name]}">
										</h:selectBooleanCheckbox>
									</c:if>
									<c:if test="#{item.type eq 'selectOneMenu'}">
										<h:selectOneMenu required="#{item.required}"
											pt:data-item="#{item.name}"
											value="#{workitem.item[item.name]}">
											<f:selectItems value="#{item.selectItems}" />
										</h:selectOneMenu>
									</c:if>
									<c:if test="#{item.type eq 'selectOneRadio'}">
										<h:selectOneRadio required="#{item.required}"
											pt:data-item="#{item.name}"
											value="#{workitem.item[item.name]}">
											<f:selectItems value="#{item.selectItems}" />
										</h:selectOneRadio>
									</c:if>
									<c:if test="#{item.type eq 'selectManyCheckbox'}">
										<h:selectManyCheckbox required="#{item.required}"
											pt:data-item="#{item.name}"
											value="#{workitem.itemListArray[item.name]}">
											<f:selectItems value="#{item.selectItems}" />
										</h:selectManyCheckbox>
									</c:if>
								</c:otherwise>
							</c:choose>
						</c:if>
					</dd>
				</dl>
			</c:forEach>
		</div>

	</c:forEach>
</ui:composition>

src/main/webapp/pages/workflow/custom_read.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	xmlns:marty="http://xmlns.jcp.org/jsf/composite/marty">

	<c:forEach items="#{customFormController.sections}" var="section">

		<div
			class="imixs-form-section#{(empty section.columns)?'':'-'.concat(section.columns)}">

			<c:if test="#{! empty section.label}">
				<h2>#{section.label}</h2>
			</c:if>

			<c:forEach items="#{section.items}" var="item">
				<dl>
					<dt>
						#{item.label}
						<c:if test="#{item.required}">
							<span class="imixs-required"> *</span>
						</c:if>
					</dt>
					<dd>
						<!-- text -->
						<c:if test="#{item.type eq 'text'}">
							<h:outputText value="#{workitem.item[item.name]}" />
						</c:if>
						
						<!-- long -->
						<c:if test="#{item.type eq 'number'}">
							<h:outputText value="#{workitem.item[item.name]}">
								<f:convertNumber/>
							</h:outputText>
						</c:if>
						
						<!-- currency -->
						<c:if test="#{item.type eq 'currency'}">
							<h:outputText value="#{workitem.item[item.name]}">
								<f:convertNumber minFractionDigits="2" locale="de" />
							</h:outputText>
						</c:if>
						
						<!-- date -->
						<c:if test="#{item.type eq 'date'}">
							<h:outputText value="#{workitem.item[item.name]}">
							   <f:convertDateTime timeZone="#{message.timeZone}"
									pattern="#{message.datePatternShort}" />
							</h:outputText>
						</c:if>
						
						<!-- text area -->
						<c:if test="#{item.type eq 'textarea'}">
							<h:outputText escape="true"
								value="#{workitem.item[item.name]}" />
						</c:if>

						<!-- HTML -->
						<c:if test="#{item.type eq 'html'}">
							<h:outputText escape="false"
								value="#{workitem.item[item.name]}" />
						</c:if>
						
						<!-- Options List -->
						<c:if test="#{item.type eq 'selectBooleanCheckbox' or item.type eq 'selectOneMenu' or item.type eq 'selectOneRadio' or item.type eq 'selectManyCheckbox'}">
							<ui:repeat var="itemvalue" value="#{workitem.itemList[item.name]}">
								<h:outputText value="#{itemvalue}"></h:outputText><br />
							</ui:repeat>
						</c:if>

					</dd>
				</dl>
			</c:forEach>
		</div>

	</c:forEach>
</ui:composition>

src/main/webapp/pages/workflow/error.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">


	<h:panelGroup rendered="#{! empty facesContext.maximumSeverity}">
		<div class="ui-widget" style="margin:20px 0;">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
				<p>
					<span class="ui-icon ui-icon-alert"
						style=" margin-right: .3em;"></span> <strong>Error:</strong>
					<h:messages />
				</p>
			</div>
		</div>
	</h:panelGroup>
</ui:composition>

src/main/webapp/pages/workflow/start.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	template="/layout/template.xhtml">




	<f:metadata>
		<f:viewAction action="#{workflowController.onLoad()}" />
	</f:metadata>



	<ui:define name="content">
		<f:view>
			<h:form id="workitem_form_id">

				<h1>Start a New Business Process</h1>
				<p class="lead">Select a Workflowgroup to start a new process:</p>


				<!-- Error  -->
				<ui:include src="error.xhtml" />


				<ul style="margin: 5px 0;">
					<ui:repeat value="#{modelController.workflowGroups}" var="group">
						<!-- get first task by group -->
						<ui:param name="model"
							value="#{modelController.getModelByGroup(group)}" />
						<ui:param name="initialTask"
							value="#{(!empty model) and (!empty model.findTasksByGroup(group))?model.findTasksByGroup(group).get(0):null}" />

						<li><h:panelGroup rendered="#{! empty initialTask}">
								<h:commandLink title=" " styleClass="action-create"
									actionListener="#{workflowController.create(model.version,initialTask.item['numprocessid'],process.item['$uniqueid'])}"
									action="/pages/workflow/workitem">
									<span class="typcn typcn-folder-add"></span>
									<h:outputText value="#{group}" />
								</h:commandLink>
									<p><h:outputText
											value="#{initialTask.item['rtfdescription']}" escape="false" />
									</p>
								<span class="imixs-tooltip"> <h:outputText
										value="#{initialTask.item['rtfdescription']}" escape="false" />
								</span>
							</h:panelGroup> <h:outputText style="color:red" rendered="#{empty initialTask}"
								value="	Missing Model Definition: #{group}"></h:outputText></li>
					</ui:repeat>
				</ul>


			</h:form>
		</f:view>
	</ui:define>

</ui:composition>

src/main/webapp/pages/workflow/sub_documents.xhtml
<f:subview xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">

	<dl>
		<dt style="clear: left;">
			<h:outputText value="#{global.attachments}" />
		</dt>
		<dd>
			<i:imixsFileUpload id="file_upload_id"
				workitem="#{workflowController.workitem}"
				context_url="#{facesContext.externalContext.requestContextPath}/api/workflow/workitem/#{workflowController.workitem.item['$uniqueid']}"
				hideatachments="false" hideuploads="false" />
		</dd>
	</dl>
	


	<!-- Documents Preview -->
	
	
	<!-- Note: the document height can be adjusted with the ui:param 'height' -->
	<script type="text/javascript">
		/*<![CDATA[*/
			
			/* reqlace special characters in attachemnt url */
		$(document).ready(
				function() {
					
					// hide documents-file-deeplink
					$("#documents-file-deeplink").hide();
					
					// update the link action for each file
					// we redirect the href into the iframe target
					$(".imixsFileUpload_uploadlist .imixsFileUpload_file").each(
						function(index, element) {
							$(this).click(function(){
								var file_link=$(this).attr('href');
								updateIframe(file_link);
								
								// update documents-file-deeplink
								$("#documents-file-deeplink").attr('href',file_link);
								$("#documents-file-deeplink").show();
								
								// cancel link
							    return false;
							});
						});

					// autoload feature - load first pdf if available
					$(".imixsFileUpload_uploadlist .imixsFileUpload_file").each(
							function(index, element) {
								var attachmentName=$(this).text();
								if (attachmentName.endsWith('.pdf') || attachmentName.endsWith('.PDF')) {									
									$(this).click();
									return false;
								}
							});
				
				
				
				});


		function updateIframe(docurl) {
			//console.log(docurl);
			$("#document_preview_helper").hide();
			var iframe = document.getElementById('imixs_dms_iframe');
			iframe.src = docurl;
		}
		/*]]>*/
	</script>


	<ui:param name="fileData" value="#{workflowController.workitem.fileData}"></ui:param>
	
	<div class="imixs-form-section imixs-form-attachments">
	
		<a href="#" class="pull-right" id="documents-file-deeplink" target="_blank"><span class="typcn typcn-cloud-storage" style="font-size:1.2em;"></span> Download</a>

		<ui:fragment rendered="#{! empty fileData}">
			<iframe id="imixs_dms_iframe" src="" width="100%" height="#{empty height?800:height}px">
			</iframe>
		</ui:fragment>
		
		
	</div>
	
	
	
	
	
</f:subview>

src/main/webapp/pages/workflow/sub_main.xhtml
<f:subview xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">

	<!-- **** General info ***** -->
	
	
	
	
	<dl>
		<dt>
			<h:outputLabel value="#{global.subject}">
				<h:message style="color: red" for="subject_id" showSummary="true"
					showDetail="false" />
			</h:outputLabel>
		</dt>
		<dd style="width: 400px;">
			<h:inputText style="width: 20em;" required="true"
				value="#{workflowController.workitem.item['subject']}"
				id="subject_id">
			</h:inputText>
		</dd>

		<dt>
			<h:outputLabel value="#{global.date}"></h:outputLabel>
		</dt>
		<dd style="width: 350px;">
			<i:imixsDateInput value="#{workflowController.workitem.item['date']}"  showtime="true" minuteinterval="5"/>
		</dd>

		<dt style="clear: left;">
			<h:outputLabel value="Team:">
				<h:message style="color: red" for="team_id" showSummary="true"
					showDetail="false" />
			</h:outputLabel>
		</dt>
		


		<dt style="clear: left;">#{global.details}</dt>
		<dd>
			<h:inputTextarea class="imixs-editor"
				value="#{workflowController.workitem.item['description']}" />

		</dd>
	</dl>

	<div style="clear: left;" />



</f:subview>

src/main/webapp/pages/workflow/workitem_chronicle.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:marty="http://xmlns.jcp.org/jsf/composite/marty"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">



	<!-- Main panel - shows entries filtered by optional category -->
	<h:panelGroup id="chronicle-main" layout="block" class="imixs-workitem-chronicle">

		<table style="width: 100%;">
			<!-- print a headline for each year -->
			<ui:repeat var="year" value="#{chronicleController.getYears()}">

				<!-- print YEAR -->
				<tr class="year">
					<td colspan="3"><h2
							style="width: 100%; text-align: center; border-bottom: 1px solid #ddd;">#{year}</h2></td>
				</tr>

				<!-- print all MONTHs -->
				<ui:repeat var="month"
					value="#{chronicleController.getMonths(year)}">
					<ui:param name="message_month" value="month_#{month}"></ui:param>
					<tr class="month">
						<td colspan="3"><h3 style="width: 100%; text-align: center;">#{message[message_month]}</h3></td>

					</tr>

					<!-- show chronic by month -->
					<ui:repeat var="chronicle"
						value="#{chronicleController.getChroniclePerMonth(year,month)}">
						<ui:include src="workitem_chronicle_entry.xhtml">
							<ui:param name="chronicle" value="#{chronicle}" />
						</ui:include>
					</ui:repeat>
				</ui:repeat>
			</ui:repeat>
		</table>
	</h:panelGroup>

</ui:composition>